"""empty message

Revision ID: 0054a26d52e1
Revises: 
Create Date: 2025-03-28 13:54:35.969913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0054a26d52e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tron',
    sa.Column('address', sa.String(length=34), nullable=True),
    sa.Column('bandwidth', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('balance_trx', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tron_address'), 'tron', ['address'], unique=True)
    op.create_index(op.f('ix_tron_id'), 'tron', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tron_id'), table_name='tron')
    op.drop_index(op.f('ix_tron_address'), table_name='tron')
    op.drop_table('tron')
    # ### end Alembic commands ###
